[general]
import = [
    "~/dotfiles/.config/alacritty/themes/kanagawa_dragon.toml"
    # "~/dotfiles/.config/alacritty/themes/gruvbox_material.toml"
]

[cursor.style]
shape = "Block"

[cursor.vi_mode_style]
shape = "Block"

[font]
size = 12

[font.normal]
family = "Fira Code"
# family = "Mononoki Nerd Font"
# family = "Iosevka"

[[keyboard.bindings]]
action = "None"
key = "N"
mods = "Command"

[window]
opacity = 1.0

[window.padding]
x = 15
y = 15
