[general]
import = [
    # "~/dotfiles/.config/alacritty/themes/kanagawa_dragon.toml"
    "~/dotfiles/.config/alacritty/themes/gruvbox_material.toml"
]

[font]
size = 11

[font.normal]
family = "Fira Code"

[[keyboard.bindings]]
action = "None"
key = "N"
mods = "Command"

[window]
opacity = 1.0

[window.padding]
x = 15
y = 15
