[general]
import = [
    "~/dotfiles/.config/alacritty/themes/gruvbox_material_hard_dark.toml"
]

[font]
size = 11

[font.normal]
family = "Fira Code"

[[keyboard.bindings]]
action = "None"
key = "N"
mods = "Command"

[window.padding]
y = 5
x = 5
