theme = "catppuccin_frappe"

[editor]
# Display any opened buffer
bufferline = "multiple"
# Highlight the cursor line
cursorline = true
# Add relative line numbers
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
